### ISSUE TITLE
Cannot enter nix-shell

### ISSUE THREAD

**Issue by bierlingm** [holochain/elemental-chat#18]
When trying to enter nix-shell, this is what it says:

![Screen Shot 2020-11-30 at 10 39 04](https://user-images.githubusercontent.com/9335771/100599842-6e601180-32f8-11eb-87b4-879920a7a65f.png)

And here's what --show-trace shows:

![Screen Shot 2020-11-30 at 10 53 45](https://user-images.githubusercontent.com/9335771/100601361-630de580-32fa-11eb-9d13-8de3dbc470f9.png)

**Comment by zo-el** [comment]
This repo does not have nix-shell set-up yet. If you want to use nix-shell for now you would have to enter into nix-shell on the holochain repo, set-up the holochain and dna_utils binary then enter this repo and run `make build`
